
name: 'Chromatic'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run : yarn test
      - uses: chromaui/action@v1
        with:
          projectToken: 2wix88i1ziu
          token: ${{ secrets.GITHUB_TOKEN }}